import type { Metadata } from "next";
import "./globals.css";

/**
 * ${1:Description placeholder}
 *
 * @type {Metadata}
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * ${1:Description placeholder}
 *
 * @export
 * @param {Readonly<{
 *   children: React.ReactNode;
 * }>} param0
 * @param {Readonly<{ children: React.ReactNode; }>\} param0.children
 * @returns {${2:*}\}
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="">{children}</div>
      </body>
    </html>
  );
}
